# Generated by Django 3.1.6 on 2021-03-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='proImg')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application5.category')),
            ],
        ),
    ]
