# Generated by Django 3.1.6 on 2021-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application5', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Number', models.IntegerField()),
                ('Message', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderImg')),
            ],
        ),
    ]
