# Generated by Django 3.1.6 on 2021-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application5', '0003_contact_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
