# Generated by Django 3.1.6 on 2021-03-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application5', '0004_register_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application5.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application5.register')),
            ],
        ),
    ]
