# Generated by Django 3.1.7 on 2021-04-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application5', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=20)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application5.register')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application5.cart')),
            ],
        ),
    ]
